[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sumgui"
version = "0.2.0a19"
description = "A tiny retro-flavored GUI toolkit for Pygame."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPL-2.0-or-later" }
authors = [{ name = "William Martinez Bas", email = "metfar@gmail.com" }]
dependencies = ["sumcore>=0.1.0a4", "sumui>=0.1.0a13", "pygame>=2.0"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: User Interfaces",
]

[project.optional-dependencies]
matplotlib = ["matplotlib>=3.7"]
seaborn = ["matplotlib>=3.7", "seaborn>=0.13"]
charts = ["matplotlib>=3.7", "seaborn>=0.13", "sumplot>=0.1.0a2"]
plots = ["sumplot>=0.1.0a2", "sumdata>=0.1.0a2"]

[project.scripts]
sumgui = "sumgui.cli:main"
sumgdialog = "sumgui.tools.gdialog:main"
sumudg = "udg_painter_reborn.udg_painter_sumgui:main"

[tool.setuptools.packages.find]
include = ["sumgui*", "udg_painter_reborn*"]

[tool.setuptools.package-data]
udg_painter_reborn = ["*.udg", "*.xpm", "*.ico", "*.png", "*.md", "LICENSE"]
